/*
 * Test data strategy for search.BinarySearch.
 *
 * Generated by JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178), 2017-10-14 19:42 -0400.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

package search.BinarySearch_JML_Data;


import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;
import search.PackageStrategy_int;
/**
 * Test data strategy for search.BinarySearch. Provides
 * class-scope test values for type int.
 * 
 * @author JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178)
 * @version 2017-10-14 19:42 -0400
 */
public /*@ nullable_by_default */ class ClassStrategy_int 
  extends PackageStrategy_int {
  /**
   * @return class-scope values for type int.
   */
  public RepeatedAccessIterator<?> classValues() {
    return new ObjectArrayIterator<Object>
    (new Object[] 
     { /* add class-scope int values or generators here */ });
  }
}
