/*
 * Test data strategy for search.BinarySearch.
 *
 * Generated by JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178), 2017-10-14 19:42 -0400.
 * (do not modify this comment, it is used by JMLUnitNG clean-up routines)
 */

 
package search.BinarySearch_JML_Data;

import org.jmlspecs.jmlunitng.iterator.ObjectArrayIterator;
import org.jmlspecs.jmlunitng.iterator.RepeatedAccessIterator;

/**
 * Test data strategy for search.BinarySearch. Provides
 * test values for parameter "int value" 
 * of method "boolean find(int[], int)". 
 * 
 * @author JMLUnitNG 1.4 (116/OpenJML-20131218-REV3178)
 * @version 2017-10-14 19:42 -0400
 */
public /*@ nullable_by_default */ class find__int1DArray_sortedValues__int_value__0__value
  extends ClassStrategy_int {
  /**
   * @return local-scope values for parameter 
   *  "int value".
   */
  public RepeatedAccessIterator<?> localValues() {
    return new ObjectArrayIterator<Object>
    (new Object[]
     { /* add local-scope int values or generators here */ });
  }
}
